//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozyBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blogs
    {
        public Blogs()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.DateTime DatePosted { get; set; }
        public string PostedBy { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
