//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozyBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public System.DateTime DatePosted { get; set; }
        public Nullable<long> QQ { get; set; }
        public string Email { get; set; }
    
        public virtual Blogs Blogs { get; set; }
    }
}
